-1: 系统繁忙
0: 请求成功
40001: 获取 access_token 时 AppSecret 错误，或者 access_token 无效
40002: 不合法的凭证类型
40003: 不合法的 OpenID
40004: 不合法的媒体文件类型
40005: 上传素材文件格式不对
40006: 上传素材文件大小超出限制
40007: 不合法的媒体文件 id
40008: 不合法的消息类型
40009: 图片尺寸太大
40010: 不合法的语音文件大小
40011: 不合法的视频文件大小
40012: 不合法的缩略图文件大小
40013: 不合法的appid
40014: 不合法的 access_token
40029: 无效的 oauth_code
40033: 不合法的请求字符，不能包含 \uxxxx 格式的字符
40090: 当前客户端ip未在开放平台白名单
40091: 无效的ticket
40094: 无效的第三方凭证
40132: 微信号不合法
42001: access_token 超时，请检查 access_token 的有效期
42002: refresh_token 超时
42003: oauth_code 超时
42007: 用户修改微信密码， accesstoken 和 refreshtoken 失效，需要重新授权
43016: 小程序未认证
45009: 接口调用超过限制
45011: API 调用太频繁，请稍候再试
85001: 微信号不存在或微信号设置为不可搜索
85002: 小程序绑定的体验者数量达到上限
85003: 微信号绑定的小程序体验者达到上限
85004: 微信号已经绑定
85007: 页面路径错误
85008: 当前小程序没有已经审核通过的类目，请添加类目成功后重试
85009: 已经有正在审核的版本
85010: 有项目为空
85011: 标题填写错误
85012: 无效的审核 id
85013: 无效的自定义配置
85014: 无效的模板编号
85015: 版本输入错误
85016: 域名数量超过限制 ，总数不能超过1000
85017: 没有新增域名，请确认小程序已经添加了域名或该域名是否没有在第三方平台添加
85018: 域名没有在第三方平台设置
85019: 没有审核版本
85020: 审核状态未满足发布
85043: 模板错误
85044: 代码包超过大小限制
85045: 有不存在的路径
85046: tabBar 中缺少 path
85047: pages 字段为空
85048: ext_json 解析失败
85049: 达到修改head img或介绍配额限制
85073: 二维码规则已满
85074: 小程序未发布, 小程序必须先发布代码才可以发布二维码跳转规则
85075: 个人类型小程序无法设置二维码规则
85077: 小程序类目信息失效（类目中含有官方下架的类目，请重新选择类目）
85079: 小程序没有线上版本，不能进行灰度
85080: 小程序提交的审核未审核通过
85081: 无效的发布比例
85082: 当前的发布比例需要比之前设置的高
85083: 搜索标记位被封禁，无法修改
85084: 非法的 status 值，只能填 0 或者 1
85085: 小程序提审数量已达本月上限，请点击查看《临时quota申请流程》
85086: 提交代码审核之前需提前上传代码
85087: 小程序已使用 api navigateToMiniProgram，请声明跳转 appid 列表后再次提交
86001: 不存在第三方的已经提交的代码
86002: 小程序还未设置昵称、头像、简介。请先设置完后再重新提交
86004: 无效的微信号
86007: 小程序禁止提交
86008: 服务商被处罚，限制全部代码提审能力
86009: 服务商新增小程序代码提审能力被限制
86010: 服务商迭代小程序代码提审能力被限制
87006: 小游戏不能提交
87007: session_key 不存在或者过期
87011: 现网已经在灰度发布，不能进行版本回退
87012: 该版本不能回退，可能的原因：1:无上一个线上版用于回退 2:此版本为已回退版本，不能回退 3:此版本为回退功能上线之前的版本，不能回退
87013: 撤回次数达到上限（每天一次，每个月 10 次）
87014: 内容不合规
89000: 该公众号/小程序已经绑定了开放平台帐号
89001: 与开放平台帐号主体不相同
89002: 该公众号/小程序未绑定微信开放平台帐号。
89003: 该开放平台帐号并非通过 api 创建，不允许操作
89004: 该开放平台帐号所绑定的公众号/小程序已达上限（100 个）
89019: 业务域名无更改，无需重复设置
89020: 尚未设置小程序业务域名，请先在第三方平台中设置小程序业务域名后在调用本接口
89021: 请求保存的域名不是第三方平台中已设置的小程序业务域名或子域名
89029: 业务域名数量超过限制，最多可以添加100个业务域名
89231: 个人小程序不支持调用 setwebviewdomain 接口
89236: 该插件不能申请
89237: 已经添加该插件
89238: 申请或使用的插件已经达到上限
89239: 该插件不存在
89243: 该申请为“待确认”状态，不可删除
89247: 该公众号/小程序 已经绑定了开放平台帐号
89250: 微信内部错误
89251: 未找到该任务
89252: 模板消息已下发，待法人人脸核身校验
89253: 法人&企业信息一致性校验中
89254: 第三方平台无权限
89255: 参数无效，请检查code长度以及内容是否正确；注意code_type的值不同需要传的code长度不一样
89256: token 信息有误
89257: 该插件版本不支持快速更新
89258: 当前小程序帐号存在灰度发布中的版本，不可操作快速更新
91001: 不是公众号快速创建的小程序
91002: 小程序发布后不可改名
91003: 改名状态不合法
91004: 昵称不合法
91005: 昵称 15 天主体保护
91006: 昵称命中微信号
91007: 昵称已被占用
91008: 昵称命中 7 天侵权保护期
91009: 需要提交材料
91010: 其他错误
91011: 查不到昵称修改审核单信息
91012: 其它错误
91013: 占用名字过多
91014: +号规则 同一类型关联名主体不一致
91015: 原始名不同类型主体不一致
91016: 名称占用者 ≥2
91017: +号规则 不同类型关联名主体不一致
91018: 组织类型小程序发布后，侵权被清空昵称，需走认证改名
91019: 小程序正在审核中
92000: 该经营资质已添加，请勿重复添加
92002: 附近地点添加数量达到上线，无法继续添加
92003: 地点已被其它小程序占用
92004: 附近功能被封禁
92005: 地点正在审核中
92006: 地点正在展示小程序
92007: 地点审核失败
92008: 小程序未展示在该地点
93009: 小程序未上架或不可见
93010: 地点不存在
93011: 个人类型小程序不可用
93012: 非普通类型小程序（门店小程序、小店小程序等）不可用
93013: 从腾讯地图获取地址详细信息失败
93014: 同一资质证件号重复添加
93015: 附近类目审核中
93016: 服务标签个数超限制（官方最多5个，自定义最多4个）
93017: 服务标签或者客服的名字不符合要求
93018: 服务能力中填写的小程序appid不是同主体小程序
93019: 申请类目之后才能添加附近地点
93020: qualification_list无效
93021: company_name字段为空
93022: credential字段为空
93023: address字段为空
93024: qualification_list字段为空
93025: 服务appid对应的path不存在
94012: appid和商户号的绑定关系不存在
